--시퀀스 삭제
DROP SEQUENCE SEQ_A_CODE;
DROP SEQUENCE SEQ_T_CODE;
DROP SEQUENCE SEQ_S_CODE;
DROP SEQUENCE SEQ_SI_CODE;
DROP SEQUENCE SEQ_CO_CODE;
DROP SEQUENCE SEQ_SU_CODE;
DROP SEQUENCE SEQ_SC_CODE;
DROP SEQUENCE SEQ_OP_CODE;
DROP SEQUENCE SEQ_OS_CODE;
DROP SEQUENCE SEQ_CL_CODE;
DROP SEQUENCE SEQ_BO_CODE;
DROP SEQUENCE SEQ_BJ_CODE;
DROP SEQUENCE SEQ_ADM_CODE;
DROP SEQUENCE SEQ_TEA_CODE;
DROP SEQUENCE SEQ_STU_CODE;


--데이터 삭제
DELETE FROM TBL_SCORE PURGE;
DELETE FROM TBL_BAEJUM PURGE;
DELETE FROM TBL_GIVEUP PURGE;
DELETE FROM TBL_SUGANG PURGE;
DELETE FROM TBL_SUBJECT PURGE;
DELETE FROM TBL_OPENCOURSE PURGE;
DELETE FROM TBL_ADMIN PURGE;
DELETE FROM TBL_TEACHERS PURGE;
DELETE FROM TBL_STUDENTS PURGE;
DELETE FROM TBL_BOOK PURGE;
DELETE FROM TBL_COURSE PURGE;
DELETE FROM TBL_CLASS PURGE;
DELETE FROM TBL_STATIC_SUBJECT PURGE;

COMMIT;


--테이블 드랍
DROP TABLE TBL_SCORE PURGE;
DROP TABLE TBL_BAEJUM PURGE;
DROP TABLE TBL_GIVEUP PURGE;
DROP TABLE TBL_SUGANG PURGE;
DROP TABLE TBL_SUBJECT PURGE;
DROP TABLE TBL_OPENCOURSE PURGE;
DROP TABLE TBL_ADMIN PURGE;
DROP TABLE TBL_TEACHERS PURGE;
DROP TABLE TBL_STUDENTS PURGE;
DROP TABLE TBL_BOOK PURGE;
DROP TABLE TBL_COURSE PURGE;
DROP TABLE TBL_CLASS PURGE;
DROP TABLE TBL_STATIC_SUBJECT PURGE;