DROP TABLE TBL_CITY CASCADE CONSTRAINTS;

--○ 실습 테이블 생성
CREATE TABLE TBL_CITY
( CITY_ID   NUMBER(5)
, CITY_LOC  VARCHAR2(10)
, CONSTRAINT CITY_ID_PK PRIMARY KEY(CITY_ID)
);
--==>> Table TBL_CITY이(가) 생성되었습니다.

DROP SEQUENCE CITYSEQ;

--○ 시퀀스 생성 
CREATE SEQUENCE CITYSEQ START WITH 0 MINVALUE 0;
--==>> Sequence CITYSEQ이(가) 생성되었습니다.

--○ 데이터 입력
INSERT INTO TBL_CITY(CITY_ID, CITY_LOC) VALUES (CITYSEQ.NEXTVAL, '강원');
INSERT INTO TBL_CITY(CITY_ID, CITY_LOC) VALUES (CITYSEQ.NEXTVAL, '경기');
INSERT INTO TBL_CITY(CITY_ID, CITY_LOC) VALUES (CITYSEQ.NEXTVAL, '경남');
INSERT INTO TBL_CITY(CITY_ID, CITY_LOC) VALUES (CITYSEQ.NEXTVAL, '경북');
INSERT INTO TBL_CITY(CITY_ID, CITY_LOC) VALUES (CITYSEQ.NEXTVAL, '부산');
INSERT INTO TBL_CITY(CITY_ID, CITY_LOC) VALUES (CITYSEQ.NEXTVAL, '서울');
INSERT INTO TBL_CITY(CITY_ID, CITY_LOC) VALUES (CITYSEQ.NEXTVAL, '인천');
INSERT INTO TBL_CITY(CITY_ID, CITY_LOC) VALUES (CITYSEQ.NEXTVAL, '전남');
INSERT INTO TBL_CITY(CITY_ID, CITY_LOC) VALUES (CITYSEQ.NEXTVAL, '전북');
INSERT INTO TBL_CITY(CITY_ID, CITY_LOC) VALUES (CITYSEQ.NEXTVAL, '제주');
INSERT INTO TBL_CITY(CITY_ID, CITY_LOC) VALUES (CITYSEQ.NEXTVAL, '충남');
INSERT INTO TBL_CITY(CITY_ID, CITY_LOC) VALUES (CITYSEQ.NEXTVAL, '충북');
--==>> 1 행 이(가) 삽입되었습니다. * 12 

--○ 커밋
COMMIT;
--==>> 커밋 완료.

DROP TABLE TBL_BUSEO CASCADE CONSTRAINTS;

--○ 실습 테이블 생성
CREATE TABLE TBL_BUSEO
( BUSEO_ID      NUMBER(5)
, BUSEO_NAME    VARCHAR2(20)
, CONSTRAINT BUSEO_BUSEO_ID_PK PRIMARY KEY(BUSEO_ID)
);
--==>> Table TBL_BUSEO이(가) 생성되었습니다.

DROP SEQUENCE BUSEOSEQ;

--○ 시퀀스 생성
CREATE SEQUENCE BUSEOSEQ START WITH 0 MINVALUE 0;
--==>> Sequence BUSEOSEQ이(가) 생성되었습니다.

--○ 데이터 입력
INSERT INTO TBL_BUSEO(BUSEO_ID, BUSEO_NAME) VALUES(BUSEOSEQ.NEXTVAL, '개발부');
INSERT INTO TBL_BUSEO(BUSEO_ID, BUSEO_NAME) VALUES(BUSEOSEQ.NEXTVAL, '기획부');
INSERT INTO TBL_BUSEO(BUSEO_ID, BUSEO_NAME) VALUES(BUSEOSEQ.NEXTVAL, '영업부');
INSERT INTO TBL_BUSEO(BUSEO_ID, BUSEO_NAME) VALUES(BUSEOSEQ.NEXTVAL, '인사부');
INSERT INTO TBL_BUSEO(BUSEO_ID, BUSEO_NAME) VALUES(BUSEOSEQ.NEXTVAL, '자재부');
INSERT INTO TBL_BUSEO(BUSEO_ID, BUSEO_NAME) VALUES(BUSEOSEQ.NEXTVAL, '총무부');
INSERT INTO TBL_BUSEO(BUSEO_ID, BUSEO_NAME) VALUES(BUSEOSEQ.NEXTVAL, '홍보부');
--==>> 1 행 이(가) 삽입되었습니다.

--○ 커밋
COMMIT;
--==>> 커밋 완료.

DROP TABLE TBL_JIKWI CASCADE CONSTRAINTS;

--○ 실습 테이블 생성
CREATE TABLE TBL_JIKWI
( JIKWI_ID      NUMBER(5)
, JIKWI_NAME    VARCHAR2(20)
, MIN_BASICPAY  NUMBER(10)
, CONSTRAINT JIKWI_JIKWI_ID_PK PRIMARY KEY(JIKWI_ID)
);
--==>> Table TBL_JIKWI이(가) 생성되었습니다.

DROP SEQUENCE JIKWISEQ;

--○ 시퀀스 생성
CREATE SEQUENCE JIKWISEQ START WITH 0 MINVALUE 0;
--==>> Sequence JIKWISEQ이(가) 생성되었습니다.

--○ 데이터 입력 
INSERT INTO TBL_JIKWI(JIKWI_ID, JIKWI_NAME, MIN_BASICPAY)
VALUES(JIKWISEQ.NEXTVAL, '사장', 4250000);
INSERT INTO TBL_JIKWI(JIKWI_ID, JIKWI_NAME, MIN_BASICPAY)
VALUES(JIKWISEQ.NEXTVAL, '전무', 3800000);
INSERT INTO TBL_JIKWI(JIKWI_ID, JIKWI_NAME, MIN_BASICPAY)
VALUES(JIKWISEQ.NEXTVAL, '상무', 3500000);
INSERT INTO TBL_JIKWI(JIKWI_ID, JIKWI_NAME, MIN_BASICPAY)
VALUES(JIKWISEQ.NEXTVAL, '이사', 3100000);
INSERT INTO TBL_JIKWI(JIKWI_ID, JIKWI_NAME, MIN_BASICPAY)
VALUES(JIKWISEQ.NEXTVAL, '부장', 2450000);
INSERT INTO TBL_JIKWI(JIKWI_ID, JIKWI_NAME, MIN_BASICPAY)
VALUES(JIKWISEQ.NEXTVAL, '차장', 2350000);
INSERT INTO TBL_JIKWI(JIKWI_ID, JIKWI_NAME, MIN_BASICPAY)
VALUES(JIKWISEQ.NEXTVAL, '과장', 2100000);
INSERT INTO TBL_JIKWI(JIKWI_ID, JIKWI_NAME, MIN_BASICPAY)
VALUES(JIKWISEQ.NEXTVAL, '대리', 1250000);
INSERT INTO TBL_JIKWI(JIKWI_ID, JIKWI_NAME, MIN_BASICPAY)
VALUES(JIKWISEQ.NEXTVAL, '사원', 840000);
--==>> 1 행 이(가) 삽입되었습니다.* 9

--○ 커밋
COMMIT;
--==>> 커밋 완료.

