-- 1. 뷰 생성.
CREATE OR REPLACE VIEW VW_SCORE_SIST_C001
AS
SELECT T1.NAME AS COURSE_NAME, T2.NAME AS SUBJECT_NAME, T4.NAME AS STUDENT_NAME, T3.STUDENT_SCORE_TOTAL, T3.STUDENT_RANK
FROM COURSE T1, SUBJECT T2, SCORE T3, USR T4
WHERE 1=1
AND T1.ID = T2.COURSE_ID
AND T2.ID = T3.SUBJECT_ID
AND T3.STUDENT_ID = 'SIST_C001'
AND T3.STUDENT_ID = T4.ID
;

-- 2. 생성된 뷰를 다른 계정에서 조회가능하도록 SELECT 권한을 대상계정에 부여.
-- EX) GRANT SELECT ON 소유계정명.시노님명 TO 대상계정명
GRANT SELECT ON VW_SCORE_SIST_C001 TO SIST_C001;