-- 관리자 접속
-- 1. 뷰 생성.
CREATE OR REPLACE VIEW VW_SCORE_SIST_C002
AS
SELECT T1.NAME AS COURSE_NAME, T2.NAME AS SUBJECT_NAME, T4.NAME AS STUDENT_NAME, T3.STUDENT_SCORE_TOTAL, T3.STUDENT_RANK
FROM COURSE T1, SUBJECT T2, SCORE T3, USR T4
WHERE 1=1
AND T1.ID = T2.COURSE_ID
AND T2.ID = T3.SUBJECT_ID
AND T3.STUDENT_ID = 'SIST_C002'
AND T3.STUDENT_ID = T4.ID
;

-- 2. 관리자의 동의어 생성.
-- EX) CREATE OR REPLACE PUBLIC SYNONYM 시노님명 FOR 소유계정명.해당객체
CREATE OR REPLACE SYNONYM SCORE_SIST_C002 FOR SIST_A001.VW_SCORE_SIST_C002;

-- 3. 사용자 계정에게 동의어 생성 권한 부여.
-- EX) GRANT CREATE SYNONYM TO 대상계정명;
GRANT CREATE SYNONYM TO SIST_C002;


-- 사용자 접속
-- 4. 사용자의 동의어 생성.
-- EX) CREATE OR REPLACE PUBLIC SYNONYM 시노님명 FOR 소유계정명.해당객체
CREATE OR REPLACE SYNONYM SCORE_SIST_C002 FOR SIST_A001.VW_SCORE_SIST_C002;


-- 관리자 접속
-- 5. 관리자의 동의어 SELECT 권한을 대상계정명에 부여.
-- EX) GRANT SELECT ON 소유계정명.시노님명 TO 대상계정명
GRANT SELECT ON SCORE_SIST_C002 TO SIST_C002;


-- 사용자 접속
-- 6. 생성된 동의어 조회.
SELECT *
FROM SCORE_SIST_C002
;
