-- 정규화 이전 모든 칼럼을 1개 테이블에 몰아넣고 고민해보기

CREATE TABLE TBL_ALL 
(
ADM_ID VARCHAR2(10) NOT NULL, 
ADM_PW NUMBER(7) NOT NULL, 
TEACHER_NM VARCHAR2(10), 
TEACHER_SSN NUMBER(7), 
TEACHER_ID NUMBER(4), 
SUBJECT_NM VARCHAR2(30), 
SUBJECT_STT_DATE VARCHAR2(8), 
SUBJECT_END_DATE VARCHAR2(8), 
SUBJECT_BOOK_NM VARCHAR2(30), 
SUBJECT_ROOM_NM VARCHAR2(30), 
COURSE_NM VARCHAR2(30), 
COURSE_STT_DATE VARCHAR2(8), 
COURSE_END_DATE VARCHAR2(8), 
STUDENT_NM VARCHAR2(10), 
STUDENT_SSN NUMBER(7), 
STUDENT_ID NUMBER(4), 
STUDENT_SCORE_ATTD NUMBER(2), 
STUDENT_SCORE_NOTE NUMBER(2), 
STUDENT_SCORE_SKILL NUMBER(2), 
STUDENT_SCORE_TOTAL NUMBER(3), 
STUDENT_GIVEUP_YN VARCHAR2(1), 
STUDENT_RANK NUMBER(2), 
STUDENT_SUBJECT_ALREADY_YN VARCHAR2(1)
);


COMMENT ON TABLE TBL_ALL  IS '정규화_이전_테이블';

COMMENT ON COLUMN TBL_ALL.ADM_ID IS '관리자ID';
 
COMMENT ON COLUMN TBL_ALL.ADM_PW IS '관리자비밀번호';
 
COMMENT ON COLUMN TBL_ALL.TEACHER_NM IS '강사명';
 
COMMENT ON COLUMN TBL_ALL.TEACHER_SSN IS '강사 민번뒷자리';
 
COMMENT ON COLUMN TBL_ALL.TEACHER_ID IS '강사ID(강사코드)';
 
COMMENT ON COLUMN TBL_ALL.SUBJECT_NM IS '과목명(=수강과목)';
 
COMMENT ON COLUMN TBL_ALL.SUBJECT_STT_DATE IS '과목기간 시작';
 
COMMENT ON COLUMN TBL_ALL.SUBJECT_END_DATE IS '과목기간 종료';
 
COMMENT ON COLUMN TBL_ALL.SUBJECT_BOOK_NM IS '교재명 ';
 
COMMENT ON COLUMN TBL_ALL.SUBJECT_ROOM_NM IS '강의실명';
 
COMMENT ON COLUMN TBL_ALL.COURSE_NM IS '과정명';
 
COMMENT ON COLUMN TBL_ALL.COURSE_STT_DATE IS '과정기간 시작';
 
COMMENT ON COLUMN TBL_ALL.COURSE_END_DATE IS '과정기간 종료';
 
COMMENT ON COLUMN TBL_ALL.STUDENT_NM IS '학생이름';
 
COMMENT ON COLUMN TBL_ALL.STUDENT_SSN IS '학생 민번뒷자리';
 
COMMENT ON COLUMN TBL_ALL.STUDENT_ID IS '학생ID(학생번호)';
 
COMMENT ON COLUMN TBL_ALL.STUDENT_SCORE_ATTD IS '학생 점수 출결';
 
COMMENT ON COLUMN TBL_ALL.STUDENT_SCORE_NOTE IS '학생 점수 필기';
 
COMMENT ON COLUMN TBL_ALL.STUDENT_SCORE_SKILL IS '학생 점수 실기';
 
COMMENT ON COLUMN TBL_ALL.STUDENT_SCORE_TOTAL IS '학생 점수 총점';
 
COMMENT ON COLUMN TBL_ALL.STUDENT_GIVEUP_YN IS '학생 중도탈락여부(Y/N)';
 
COMMENT ON COLUMN TBL_ALL.STUDENT_RANK IS '학생 등수';
 
COMMENT ON COLUMN TBL_ALL.STUDENT_SUBJECT_ALREADY_YN IS '학생 이미수강한과목(Y/N)';